sudo: false
language: node_js
node_js:
  - "6"

before_install:
  - npm install npm@latest -g
  - npm install -g firebase-tools

script:
  - node --version
  - npm --version
  - yarn run build

after_success:
  - firebase deploy --token $FIREBASE_TOKEN
